url: "https://новыйгороф33.рф"
baseurl: ""
title: "Производство тротуарной плитки ООО «Новый город»"
keywords: "Тротуарная плитка, производство тротуарной плитки, тротуарная плитка от производителя"
description: "ООО «Новый Город» занимается производством и продажей тротуарной плитки. У нас вы можете выгодно и недорого купить тротуарную плитку от производителя"
email: "info@новыйгороф33.рф"

markdown: "kramdown"
permalink: "/:categories/:title/"
timezone: "+0300"
encoding: "utf-8"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: "offer"
